name = "youtube-downloader"
main = "functions/[[routes]].js"
compatibility_date = "2024-01-01"

[vars]
YOUTUBE_API_KEY = ""  # 将在Cloudflare Dashboard中设置

[[routes]]
pattern = "/api/*"
zone_name = "your-domain.com" 